Kong/lua-resty-aws

- src/resty/aws/init.lua
- update_api_files.sh
Reduce memory usage.
Similar to https://github.com/Kong/lua-resty-gcp/pull/7.
```lua
setmetatable(_G, nil) -- disable global warnings
ngx.update_time()
local start = ngx.now()
collectgarbage()
print("before require: ", collectgarbage("count"))
local AWS = require("resty.aws")
local EnvironmentCredentials = require "resty.aws.credentials.EnvironmentCredentials"
print("after require: ", collectgarbage("count"))
local aws = AWS({ credentials = EnvironmentCredentials.new() })
print("after initializing: ", collectgarbage("count"))
local other = AWS({ credentials = EnvironmentCredentials.new() })
print("after creating another instance: ", collectgarbage("count"))
aws = nil
other = nil
collectgarbage("collect")
print("after garbage collection: ", collectgarbage("count"))
ngx.update_time() …
```
> feat(*) lazy load api

- src/resty/aws/config.lua
- src/resty/aws/utils.lua
I accidentally caught this by testing the lib in the ECS environment, logs show that 
```
2022/09/22 08:19:18 [debug] 1#0: [lua] utils.lua:180: detect_region(): no AWS_REGION env variable
2022/09/22 08:19:18 [debug] 1#0: [lua] utils.lua:188: detect_region(): no AWS_DEFAULT_REGION env variable
2022/09/22 08:19:18 [debug] 1#0: [lua] utils.lua:201: detect_region(): no ECS_CONTAINERMETADATA_URI_V4 env variable
2022/09/22 08:19:18 [debug] 1#0: [lua] utils.lua:214: detect_region(): no ECS_CONTAINERMETADATA_URI env variable
```
The environment variable name for the ECS metadata URI seems to be wrong.
It should be `ECS_CONTAINER_METADATA_URI` and `ECS_CONTAINER_METADATA_URI_V4`, according to https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-metadata-endpoint-v4.html#task-metadata-en …
> fix: correct ecs environment variable name

- README.md
- src/resty/aws/request/build.lua
> fix: request uri build handling of + in template

- README.md
- spec/02-requests/02-build_request_spec.lua
- spec/03-credentials/08-SharedFileCredentials_spec.lua
- spec/04-services/01-secret_manager.lua
- spec/04-services/02-s3.lua
- spec/04-services/03-s3_compat_api.lua
- src/resty/aws/credentials/CredentialProviderChain.lua
- src/resty/aws/credentials/SharedFileCredentials.lua
- src/resty/aws/init.lua
- src/resty/aws/request/build.lua
- src/resty/aws/request/sign.lua
- src/resty/aws/request/signatures/none.lua
- src/resty/aws/request/signatures/v4.lua
- src/resty/aws/request/validate.lua
fix: template incorrect handling of query string 
fix: blob param should be raw body
feat: add support for credential from file 
fix: escaping for param in uri
fix: handling raw body conflict with body param
fix: crash when no type check designated
fix: missing support for "headers" location
fix: compatibility for S3
> Bug fixes and features for S3 support

- README.md
- spec/02-requests/02-build_request_spec.lua
- spec/04-services/02-s3.lua
- spec/04-services/03-s3_compat_api.lua
- src/resty/aws/request/build.lua
> fix(config): auto detection and default to tls

- README.md
- src/resty/aws/init.lua
> fix(STS) fix duplicate regions causing bad hostnames

- README.md
- src/resty/aws/service/rds/signer.lua
This PR fixes a problem that the rds signer cannot be used in init phase.
```
2023/04/17 13:11:45 [error] 784916#0: init_by_lua error: ./kong/globalpatches.lua:576: no request found
stack traceback:
[C]: in function 'old_tcp'
./kong/globalpatches.lua:576: in function 'ngx_socket_tcp'
...ee/bazel-bin/build/kong-dev/share/lua/5.1/resty/http.lua:133: in function 'new'
.../kong-dev/share/lua/5.1/resty/aws/service/rds/signer.lua:9: in main chunk
[C]: in function 'require'
...azel-bin/build/kong-dev/share/lua/5.1/resty/aws/init.lua:467: in function 'RDS'
./kong/db/strategies/postgres/iam_token_handler.lua:32: in function 'init'
./kong/db/strategies/postgres/connector.lua:1071: in function 'new'
./kong/db/strategies/init.lua:37: in function 'new'
./kong/db/init.lua:95: in function 'new' …
```
> fix(rds): fix rds signer cannot be used in init phase

- README.md
- lua-resty-aws-dev-1.rockspec.template
This PR adds the SharedFileCredentials into rockspec so it can be packed and used correctly.
Currently it will not be installed by luarock
FTI-5045
> fix: add SharedFileCredentials into rockspec

- README.md
- src/resty/aws/credentials/ChainableTemporaryCredentials.lua
Fixes an error: 
```
key 'AssumeRole' not found, did you mean 'assumeRole'?
```
@Tieske - I was hoping to work on [this Kong issue](https://github.com/Kong/kong/issues/7638) but need this fixed and released before ChainableTemporaryCredentials is usable.
> Fix assumeRole function name on STS

- README.md
- spec/03-credentials/04-RemoteCredentials_spec.lua
- src/resty/aws/credentials/RemoteCredentials.lua
The RemoteCredential does not support a full URI with port number now, the error log shows as follow:
```
2023/07/27 15:48:41 [debug] 46876#0: [lua] RemoteCredentials.lua:70: Failed to construct RemoteCredentials url: Unsupported hostname: AWS.RemoteCredentials only supports localhost,127.0.0.1 for http; http://localhost requested.
```
It seems that the code is using wrong reference for host, it should be `host` instead of `hostname`.
The document of socket.url.parse: 
```
url.parse(url, default)
Parses an URL given as a string into a Lua table with its components.
Url is the URL to be parsed. If the default table is present, it is used to store the parsed fields. Only fields present in the URL are overwritten. Therefore, this table can be used to pass default values for each field.
The …
```
> fix(*): fix AWS_CONTAINER_CREDENTIALS_FULL_URI parsing

- src/resty/aws/credentials/ChainableTemporaryCredentials.lua
References and documentation for `ChainedTemporaryCredentials` updated to `ChainableTemporaryCredentials` which actually exists.
The next `make docs` will generate correct documentation files.
> docs(credential): ChainedTemporaryCredentials -> ChainableTemporaryCredentials

- README.md
- spec/02-requests/03-execute_spec.lua
- src/resty/aws/init.lua
- src/resty/aws/request/execute.lua
- src/resty/aws/request/signatures/presign.lua
- src/resty/aws/request/signatures/v4.lua
This PR adds support for configuring multiple network options on service request, including:
- ssl_verify open or not
- TCP overall timeout
- TCP keepalive idle timeout - (https://github.com/openresty/lua-nginx-module#tcpsocksetkeepalive)
KAG-2242
> feat(*): support configure multiple network options

- spec/02-requests/03-execute_spec.lua
- src/resty/aws/config.lua
- src/resty/aws/request/execute.lua
- src/resty/aws/request/signatures/presign.lua
- src/resty/aws/request/signatures/v4.lua
This PR adds support for using HTTP/HTTPS proxy on service requests. Proxies that are defined in the environment variable will also take effect, to keep aligned with https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-proxy.html
Note that most of the credential fetch-related requests (except the one that hit STS) will not use this proxy deliberately, as I thought it is very rare for those environment-related requests to have a need to use proxy
KAG-1621
FTI-5242
#2
> feat(*): add http/https proxy support for service request

- README.md
- spec/03-credentials/02-EC2MetadataCredentials_spec.lua
- src/resty/aws/credentials/EC2MetadataCredentials.lua
This PR adds support for using IMDSv2 service in EC2 metadata credential provider. Manually tested with IMDSv2 optional and IMDSv2 required.
FTI-5232
This PR also adds more error handling into EC2 metadata credential provider. Ref: https://docs.aws.amazon.com/IAM/latest/UserGuide/troubleshoot_iam-ec2.html (see the section `The iam/security-credentials/[role-name] document indicates "Code":"AssumeRoleUnauthorizedAccess"`)
FTI-5232
> feat(*): EC2 metadata credential provider support IMDSv2

- README.md
- src/resty/aws/request/signatures/utils.lua
This PR ensures that `canonicalise_query_string` should always return a URL encoded format query string. Currently when `query` is a table, the value will not be encoded again. This makes the STS assumeRole not working since assumeRole requires a IAM ARN which contains colon that should be URL encoded. Calling STS assumeRole will return signature not match error without the PR's fix.
> fix(*): fix v4 signing request should correctly canonicalized query table as well

- README.md
- src/resty/aws/request/signatures/none.lua
FTI-5242
This is an urgent blocker for lambda feature development. Prerequisite for https://github.com/Kong/kong/pull/11551
> fix(signature): none-signature(unsigned) should support network related config options as well

- README.md
- src/resty/aws/utils.lua
… and advise against trying to
> fix(*): don't invoke region detection code on the module toplevel

- src/resty/aws/credentials/CredentialProviderChain.lua
- src/resty/aws/credentials/RemoteCredentials.lua
- src/resty/aws/init.lua
- src/resty/aws/request/validate.lua
Moves the code that was previously running on `module` level to `initialize` function that are lazily called when needed. This is to avoid the `yield accross C-boundary` errors during `require`.
> fix(*): lazily initialize structures to avoid c-boundary errors on require

- README.md
- src/resty/aws/request/validate.lua
APIs listed below is unavailable due to unsupported filed for the validator.
listObjectsV2
getBucketLifecycleConfiguration
putBucketLifecycleConfiguration
> fix(validate): unsupport fields

- spec/03-credentials/08-SharedFileCredentials_spec.lua
- src/resty/aws/config.lua
Base on https://github.com/lunarmodules/luafilesystem/issues/172, seem `pl.isfile` and `pl.isdif` will return the wrong result if the path start with "~"
currently I can confirm there's a bug when load cred file:
```
local credential = require("resty.aws.config").load_credentials_file("~/.aws/credentials", "xxxprofile")
```
Above I got nil caused by [here](https://github.com/Kong/lua-resty-aws/blob/main/src/resty/aws/config.lua#L172-L173), however, I am sure my credentials file exist and format is definitely correct. So I raised the https://github.com/lunarmodules/luafilesystem/issues/172 issue. Not sure how and when they fix it but we can safely fix this issue by an absolute path.
> fix pl.path can't resolve the path started with ~

- README.md
- update_api_files.sh
In the AWS SDK, there is sample access key sample `wJalrXUtnFEMI` that may trigger CVE report. This PR tries to remove it.
This is a dangerous operation! Before merge, we must ensure only the access key sample is removed!
FTI-5732 FTI-5732
> chore(*): remove sample access key from SDK documentation

- README.md
- spec/03-credentials/04-RemoteCredentials_spec.lua
- src/resty/aws/config.lua
- src/resty/aws/credentials/RemoteCredentials.lua
This PR adds support for using authorization token in Container Credential Provider. Container Credential Provider uses two environment variables for the auth token content: `AWS_CONTAINER_AUTHORIZATION_TOKEN`(for token value)  and `AWS_CONTAINER_AUTHORIZATION_TOKEN_FILE`(for a file path that stores token value). See https://docs.aws.amazon.com/sdkref/latest/guide/feature-container-credentials.html. If one of the token env vars exists, the token value will be used as `Authorization` header value when requesting credential provider URI.
By adding support for auth token in Container Credential Provider, we can support the latest "Pod Identity" IAM Auth method in AWS EKS. See [How EKS Pod Identity works](https://docs.aws.amazon.com/eks/latest/userguide/pod-id-how-it-works.html)
Reference: …
> feat: container credential provider support auth token

- README.md
- src/resty/aws/init.lua
- src/resty/aws/request/build.lua
If no inputs were available, this would throw hard errors.
> fix(request): anticipate operations with no inputs

- README.md
- spec/01-generic/01-config_spec.lua
- spec/03-credentials/04-RemoteCredentials_spec.lua
- spec/03-credentials/08-SharedFileCredentials_spec.lua
- src/resty/aws/config.lua
`pl.path.expanduser` may return with `nil, err` when received a path argument starting with `~` but `$HOME`(or other home path related) environment variable is not present. This PR adds proper error handling code when calling `expanduser`.
> fix(*): patch expanduser to be more friendly to OpenResty environment

- README.md
- spec/02-requests/03-execute_spec.lua
- src/resty/aws/request/execute.lua
This PR enables `cjson.decode_array_with_array_mt(true)` in the request executes, so that further `encode` on the response body may be able to transform an empty array back to the correct array format in plain JSON text.
FTI-5937
> feat(*): decode api response json body with array metatable

- README.md
- spec/01-generic/02-aws_spec.lua
- src/resty/aws/init.lua
AWS services can be used inside a private VPC without Internet access by creating private links(VPC endpoints). When creating VPC endpoint for an AWS service, the `Enable private DNS name` is enabled by default, which means that a private DNS record will be created whose value is just the same as the AWS service's public endpoint(for example, `s3.amazonaws.com`) but pointing at the private VPC endpoint. This is what is expected to be a common practice when using VPC endpoint to access AWS service.
However, user can also disable it to not create this "fake" DNS record, and use the VPC endpoint hostname directly(something like `vpce-abcdefghijklmn-abcdefg.sts.us-east-1.vpce.amazonaws.com`). In this case, there is no need to inject region info into the endpoint domain since the hostname …
> fix(sts): do not inject region info for STS service with VPC endpoint hostname

- README.md
- spec/02-requests/02-build_request_spec.lua
- src/resty/aws/request/build.lua
previously a "blob" type without location given would be added as a nested data element which was incorrect.
fixes #58
> fix(request): unspecified location goes in body, also for blob

- spec/04-services/05-sts_spec.lua
- src/resty/aws/init.lua
This PR fixes the STS regional injection logic under the following cases:
- When `AWS_STS_REGIONAL_ENDPOINTS` is `regional`, the `service.signingRegion` must be the same as the current environment's region, instead of the `globalSSL`'s `us-east-1` region defined in the global region rule. This ensures that the API request sent to the regional STS endpoint has the correct signature.
- When `AWS_STS_REGIONAL_ENDPOINTS` is `regional` and user defines the same regional STS domain(for example, `sts.us-east-2.amazonaws.com`), ensures that the region is not being injected again inside the regional STS domain.
This PR also adds unit tests to ensure the region is defined correctly in the signed request and the endpoint is also expected under several combinations of `region`, …
> fix(sts): fix sts regional endpoint injection under several cases

- README.md
- spec/02-requests/02-build_request_spec.lua
- src/resty/aws/request/build.lua
This is a follow-up fix for #120 . 
The PR modifies the request build again with the following changes: when the `payload` field is specified inside the input schema, the request body will be built based on the parameter that specified by the `payload` field.
This behavior imitates the behavior defined in `aws-sdk-js`: https://github.com/aws/aws-sdk-js/blob/02153340ce052614c5437fe46ab1f49bfd8483f7/lib/protocol/rest_json.js#L24-L41
as well as https://github.com/aws/aws-sdk-js/blob/02153340ce052614c5437fe46ab1f49bfd8483f7/lib/protocol/rest_xml.js#L10-L26
This fixes the breaking change behavior found here: https://github.com/Kong/kong/pull/13433
FTI-6138
> fix(request): build request body by operation payload field

- spec/04-services/05-sts_spec.lua
- src/resty/aws/init.lua
This PR fixes a bug inside `generateRegionPrefix` that caused some service endpoint in specific region is not getting configured correctly.
https://github.com/Kong/lua-resty-aws/blob/50d9f0849eb03d4c2a3d7cc8a8cd10344a14df12/src/resty/aws/init.lua#L138-L149
This code originates from the [JS code here](https://github.com/aws/aws-sdk-js/blob/c0ec9d31057748cda57eac863273f5ef5a695782/lib/region_config.js#L4-L9):
```
function generateRegionPrefix(region) {
if (!region) return null;
var parts = region.split('-');
if (parts.length < 3) return null;
return parts.slice(0, parts.length - 2).join('-') + '-*';
}
```
There is a bug in our Lua code, that `parts.slice(0, parts.length - 2).join('-') + '-*'` is fetching the `[0, #parts-2)` items from the region parts and concatenating with another …
> fix(region_config): fix configure endpoint bug in getRegionPrefix
